AWSTemplateFormatVersion: 2010-09-09
Description: 'sv4 test simple nesting master'
Parameters:
  KeyPairName:
    Type: String
  VPCID:
    Type: String
  SubnetId:
    Type: String
Mappings:
  AWSAMIRegionMap:
    ap-northeast-1:
      AMZNLINUXHVM: ami-02ddf94e5edc8e904
    ap-northeast-2:
      AMZNLINUXHVM: ami-0ecd78c22823e02ef
    ap-south-1:
      AMZNLINUXHVM: ami-05695932c5299858a
    ap-southeast-1:
      AMZNLINUXHVM: ami-043afc2b8b6cfba5c
    ap-southeast-2:
      AMZNLINUXHVM: ami-01393ce9a3ca55d67
    ca-central-1:
      AMZNLINUXHVM: ami-0fa94ecf2fef3420b
    eu-central-1:
      AMZNLINUXHVM: ami-0ba441bdd9e494102
    eu-north-1:
      AMZNLINUXHVM: ami-01a7a49829bda9d79
    eu-west-1:
      AMZNLINUXHVM: ami-0e61341fa75fcaa18
    eu-west-2:
      AMZNLINUXHVM: ami-050b8344d77081f4b
    eu-west-3:
      AMZNLINUXHVM: ami-053418e626d0549fc
    sa-east-1:
      AMZNLINUXHVM: ami-05b7dbc290217250d
    us-east-1:
      AMZNLINUXHVM: ami-0e2ff28bfb72a4e45
    us-east-2:
      AMZNLINUXHVM: ami-0998bf58313ab53da
    us-west-1:
      AMZNLINUXHVM: ami-021bb9f371690f97a
    ap-northeast-3:
      AMZNLINUXHVM: ami-070b2e2b6cf47b7ba
    us-west-2:
      AMZNLINUXHVM: ami-079f731edfe27c29c
    me-south-1:
      AMZNLINUXHVM: ami-07a246cb94128dd8f
    ap-east-1:
      AMZNLINUXHVM: ami-024f2681e93e91a81
Resources:
  RootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Principal:
              Service: ec2.amazonaws.com
            Effect: Allow
            Sid: ''
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:GetObject'
                Resource: !Sub
                  - 'arn:${AWS::Partition}:s3:::${S3Bucket}/${KeyPrefix}*'
                  - S3Bucket: <THIS_VALUE_GETS_REPLACED>
                Effect: Allow
          PolicyName: AuthenticatedS3GetObjects
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref RootRole
  InstanceSecurityGroup:
    Properties:
      GroupDescription: 'ssh access to instance'
      SecurityGroupIngress:
        - CidrIp: 10.0.0.0/16
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
      VpcId: !Ref VPCID
    Type: 'AWS::EC2::SecurityGroup'
  ExampleInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      IamInstanceProfile: !Ref RootInstanceProfile
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - AMZNLINUXHVM
      InstanceType: t3.large
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      SubnetId: !Ref SubnetId
      UserData: !Base64
        Fn::Sub:
        - |
          #!/bin/bash -x
          aws s3 cp s3://${S3Bucket}/${KeyPrefix}print_stdout.sh ./
          chmod +x ./print_stdout.sh
          ./print_stdout.sh
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource ExampleInstance
        - S3Bucket: <THIS_VALUE_GETS_REPLACED>
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT15M
