Description: "Master (+VPC) Template using Sigv4 S3 URLS"
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Simple test parameter
        Parameters:
          - ParameterValue
    ParameterLabels:
      ParameterValue:
        default: Value from master template
Parameters:
  ParameterValue:
    Description: This is the parameter that we will be passing in from the master template
    Type: String
Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: Sig2SigV4Testing
      Type: String
      Value: !Ref "ParameterValue"
      Description: SSM Parameter from master stack.
      AllowedPattern: "^[a-zA-Z]{1,10}$"
      Tags:
        Environment: DEV
Outputs:
  ParameterValue:
    Description: The parameter we created based on the incoming value
    Value: !GetAtt BasicParameter.Value
