AWSTemplateFormatVersion: 2010-09-09
Description: Master (+VPC) Template using Sigv4 S3 URLS (qs-1qkt867sp)
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Simple test parameter
        Parameters:
          - SSMParameterValue
    ParameterLabels:
      SSMParameterValue:
        default: Value from master template
Parameters:
  SSMParameterValue:
    Description: This is the parameter that we will be passing in from the master template
    Type: String
Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${AWS::StackName}-SV2SV4Testing"
      Type: String
      Value: !Ref "SSMParameterValue"
      Description: SSM Parameter from master stack.
      Tags:
        Environment: DEV
Outputs:
  ParameterName:
    Description: The parameter we created based on the incoming value
    Value: !Sub "${AWS::StackName}-SV2SV4Testing"
  ParameterValue:
    Description: The parameter we created based on the incoming value
    Value: !GetAtt BasicParameter.Value
